version: build-{build}-{branch}

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - RUBY_VERSION: 200
    - RUBY_VERSION: 200-x64
    - RUBY_VERSION: 21
    - RUBY_VERSION: 21-x64
    - RUBY_VERSION: 22
    - RUBY_VERSION: 22-x64
    - RUBY_VERSION: 23
    - RUBY_VERSION: 23-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install gitv
  - bundle install --with="development test"

before_build:

build_script: rake

skip_commits:
  message: /\[ci skip\]/

notifications:
  - provider: Email
    to: rbld-devel@rbld.io
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
